### ISSUE TITLE
List of URLs

### ISSUE THREAD

**Issue by krtek4** [liip/TheA11yMachine#10]
Currently the tool only accept an URL that is then crawled. In some cases it would be a lot more efficient if we could provide a list of URLs to better target the pages that need to be tested.

**Comment by jeanmonod** [comment]
This is really important :+1:

**Comment by Hywan** [comment]
We could start with a first URL and put the other ones directly in the queue. Thoughts?

**Comment by Hywan** [comment]
And in CLI, we can read in STDIN.
