### ISSUE TITLE
Document how to fetch websites with basic auth

### ISSUE THREAD

**Issue by julmot** [liip/TheA11yMachine#107]
Our development servers are protected with basic auth. I'd like to test them but the tool only answers `failed to fetch (status code: 401)`.

**Comment by sparshi** [comment]
You need to provide auth username and password from command line

e.g. $ a11ym https://www.test.com --http-auth-user <http_auth_user> --http-auth-password <http_auth_password>

**Comment by Hywan** [comment]
I haven't seen your question, sorry.

@sparshi is right :+1:

**Comment by julmot** [comment]
There's no question, it's more a solicitation

> Document how to fetch websites with basic auth

**Comment by julmot** [comment]
I mean something like a dedicated `basic auth` section. However, as you've at least documented `--http-auth-user <http_auth_user>          Username to authenticate all HTTP requests.` it's fine for me currently.
