### ISSUE TITLE
SaaS version of the tool ?

### ISSUE THREAD

**Issue by krtek4** [liip/TheA11yMachine#11]
Seems to be a demand : https://twitter.com/bitfalls/status/684993843029250048

Let's discuss this and list what need to be done for it to happen !

**Comment by Hywan** [comment]
First, we might run thousands of PhantomJS instances… Is it something we would like to do :-p?

**Comment by krtek4** [comment]
After discussing a bit IRL with @Hywan and @jeanmonod, here are some thoughts :

* Writing a web interface to the tool is currently out of scope of this project
* The tool in itself does not require particular new features to work in a SaaS environement
* Spinning a lot of PhantomJS instance might be a scalability issues
* We would need to rate limit heavily depending on hardware.
* #18 might be nice to ease the development of a Web interface to the tool

We actively encourage anyone willing to host the tool to try and will help any effort in this direction, however our own focus and needs are more for a CLI tool right now so this is where we will put the most efforts.

**Comment by dfeyer** [comment]
Hi, first thanks top opensource this really nice tools, i'm interested in a not really SaaS but at least an API version of the service. Is it possible to have the report in JSON format, like this we can integrate it with other tools ? I'm really interested to integrate the machine with Neos CMS, it can be a really nice helper during dev to have accessibility report directly in the Neos UI, without an external HTML report.

**Comment by Hywan** [comment]
Hello :-),

Yes probably. Instead of storing the results as plain HTML, we could also store the JSON source. Are you willing to make a PR :-)?

**Comment by drixselecta** [comment]
The API light option is partly covered, as there already is an option to store the report in JSON instead of HTML `-r json` or  `--report json`.

Liip is working on a SaaS client on top of A11ym, I am thus closing this issue for now as a duplicate. @dfeyer if you are still interested in including a11ym into Neos CMS, we could discuss ways to integrate.
