### ISSUE TITLE
Note codes does not display on the index on Chrome

### ISSUE THREAD

**Issue by krtek4** [liip/TheA11yMachine#12]
The error code from a report does not display for me on the index page with the latest stable Chrome version.

Will investigate a bit more and report my findinds here.

**Comment by Hywan** [comment]
I cannot reproduce with Chromium 45. Can you investigate a little bit please?

**Comment by krtek4** [comment]
Seems there's an issue with `Set` in the nodejs version we are using (`0.12.9`)

I don't really have time to dig in, but using an array works, I'll propose a PR.
