### ISSUE TITLE
Remove crypto package and use native Node.js API instead

### ISSUE THREAD

**Issue by paazmaya** [liip/TheA11yMachine#129]
Currently there seems to be `crypto` package version `0.0.3` in use, which also generates the following output when doing `npm install`:

```sh
npm WARN deprecated crypto@0.0.3: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
```

https://nodejs.org/docs/v0.12.9/api/crypto.html

**Comment by Hywan** [comment]
Closed by #130.
