### ISSUE TITLE
Better algorithm to explore a web application

### ISSUE THREAD

**Issue by jeanmonod** [liip/TheA11yMachine#20]
I'm not sure how the actual queue is working, maybe it's just a FIFO. A website is most of the time composed by several pages generated by some dynamic templates. And most of the time a categories of page share the same template. As your goal is to find as fast as possible all the a11y issues coming from the several templates, we should try to be more clever to select the page to process.
Hopefully, most of the time, the categorisation of the pages is also reflected in the urls. So when the crawler generate a list of pages such as

    /contact
    /faq
    /product/a
    /product/b
    /home
    /product/c
    /person/1
    /person/2
    /person/3

We should then process them is this order

    /contact
    /faq
    /product/a
    /home
    /person/1
    /product/b
    /person/2
    /product/c
    /person/3

I don't know yet what formula to use, something like similarity to already parsed urls, but this could be a nice addition...

**Comment by Hywan** [comment]
Hmm, this is going to be very difficult. We must define the algorithm first. One might be clever is to sort by “difference”/delta:
> The more the page is different from others, the more it bubbles up in the queue.

To compute the delta between 2 pages, we can use the URL or the content length. Thoughts?

**Comment by Hywan** [comment]
The goal of this issue is to quickly explore a web application.

**Comment by jeanmonod** [comment]
> To compute the delta between 2 pages, we can use the URL or the content length. Thoughts?

We have the url yet, computing on page size could be great but will require an HTTP HEAD call, this could slow down the process...

**Comment by Hywan** [comment]
I am pretty sure we already have this information since we are already filtering by content-type.

**Comment by krtek4** [comment]
Bucket 4tw

**Comment by Hywan** [comment]
No that's fine. Let's go!
