### ISSUE TITLE
Refresh url button (re-run audit for a given page)

### ISSUE THREAD

**Issue by jeanmonod** [liip/TheA11yMachine#22]
Follow #8 it could be great to have a button to refresh the status of a given page

**Comment by Hywan** [comment]
I am pretty sure developer knows how to refresh their page :-p. #19 is much useful than this one :-). I am going to close this issue in favor of #19 :-).

**Comment by jeanmonod** [comment]
Sorry, my request was not clear. I was not thinking about a page refresh, but about an "url audit re-run". The idea is that you generate a report. And then from the report, you re-run the audit of a given page. What we should do:
* Provide a button
* On click, it will re-run the audit of the given url
* Once audit done, the html report is update

**Comment by krtek4** [comment]
In this case it is a duplicated of #18  which is not yet clear ;)
