### ISSUE TITLE
Improve report generation workflow / Templating Engine

### ISSUE THREAD

**Issue by krtek4** [liip/TheA11yMachine#7]
There is currently a lot of duplication between the templates and the CSS / JS. Maintenance and new feature development is difficult.

Using a real templating engine would allow us to :

* keep all the CSS and JS in separate files and include them when needed in the generate HTML.
* create templates for common part and include them (partials)
* have a better  `context` management (support for nested objects for example)

I like the fact that each report is "standalone" (no need for an external CSS or JS file), so the template engine should be able to include the CSS and JS as part of the generated page.

One possible option could to simply use the `template` feature included in http://underscorejs.org/#template

**Comment by Hywan** [comment]
We can ask @LeBenLeBen for any **very light** templating engines?

Our constraint is the following: Any report page must be standalone to be sent by emails.

**Comment by krtek4** [comment]
http://underscorejs.org/#template

**Comment by Hywan** [comment]
@krtek4 What do you think: Do we target 0.6.0 or 0.7.0?

**Comment by krtek4** [comment]
I think that I don't really care, we have time and motivation so let's put as much feature as possible in the next version ;)

0.6.0 or 0.7.0 seems completely artificial to me ;)

**Comment by Hywan** [comment]
I prefer small releases but yes, this is more or less artificial :-).
