### ISSUE TITLE
Have config file

### ISSUE THREAD

**Issue by bikasv** [liip/TheA11yMachine#72]
Hi,
There should be an option for config file and reading form it.

Currently, npm script gets too long with all the parameters. Instead we can do the following, package.json will be quite clean

a11y --config config_file.js(json?)

**Comment by Hywan** [comment]
Not sure to do this right now, but this is not a bad idea. Putting this issue as ready.

**Comment by bikasv** [comment]
There can be 2 solutions to this -

1. Use yargs to read js(on) file and then use those object as config.
2. Provide node interface so that we can write, say, a11y.js and configure everything from there. Then from script we can call `node a11y.js`.
