### ISSUE TITLE
"npm WARN ENOENT ENOENT: no such file or directory" when installing

### ISSUE THREAD

**Issue by jmuheim** [liip/TheA11yMachine#75]
```
josh@Macbuech:~/Documents/Work/MuheimWebdesign/pimp$ npm install the-a11y-machine
/Users/josh/Documents/Work/MuheimWebdesign/pimp
└─┬ the-a11y-machine@0.8.3 
  └── HTML_CodeSniffer@2.0.7  (git+https://github.com/squizlabs/HTML_CodeSniffer.git#c973a8ab99bcb3bb2a219a21465247758682e985)

npm WARN ENOENT ENOENT: no such file or directory, open '/Users/josh/Documents/Work/MuheimWebdesign/pimp/package.json'
npm WARN EPACKAGEJSON pimp No description
npm WARN EPACKAGEJSON pimp No repository field.
npm WARN EPACKAGEJSON pimp No README data
npm WARN EPACKAGEJSON pimp No license field.
```

When I do `$ npm install --global the-a11y-machine`, it works.

But then when running, I don't find the output:

```
josh@Macbuech:~/Documents/Work/MuheimWebdesign/pimp$ a11ym http://ag.ch
Initializing with http://ag.ch.
Fetching https://www.ag.ch/.
Fetching https://www.ag.ch/de/startseite_portal/startseite_portal.jsp.
Fetch complete for https://www.ag.ch/de/startseite_portal/startseite_portal.jsp.
Waiting to run https://www.ag.ch/de/startseite_portal/startseite_portal.jsp.
 1/128  Run: https://www.ag.ch/de/startseite_portal/startseite_portal.jsp.
josh@Macbuech:~/Documents/Work/MuheimWebdesign/pimp$
```

In the same folder there's no `a11ym_output` folder. Also, the output above doesn't really look like the task finishes correctly...?

**Comment by jmuheim** [comment]
I also tried it on a windows machine, and it's exactly the same there.

**Comment by Hywan** [comment]
Hello,

For the npm error, you should create a `package.json` file. Try `npm install --save the-a11y-machine`. When installing globally, a `package.json` file is created somewhere nearby your home directory, so you don't have this error.

If the tests stop running suddenly, you can incriminate PhantomJS quite easily most of the time :-/. What version of PhantomJS are you running?

**Comment by jmuheim** [comment]
Both OSX and Win:

```
$ phantomjs -v
2.1.1
```

I use PhantomJS heavily for feature tests in Rails projects, and it works flawlessly there.

**Comment by Hywan** [comment]
Same here. OK, I will try as soon as I have time!

**Comment by jasonday** [comment]
I'm seeing this issue still:

```
 ENOENT: no such file or directory, open C:\users\spjbd\package.json
No description
No repository field.
No README data
No license field.
```

**Comment by Hywan** [comment]
@jasonday https://github.com/liip/TheA11yMachine/issues/75#issuecomment-260902328 for the `package.json` issue. This is not related to this project.
