### ISSUE TITLE
opentransportdata.swiss is not recursively crawled

### ISSUE THREAD

**Issue by fanderegg** [liip/TheA11yMachine#78]
The website https://opentransportdata.swiss/ is not recursively crawled. Only the links of the language switcher are recognized and crawled, but after that is stops. Command used:

a11ym https://opentransportdata.swiss/ -o out 

The website consists of two different softwares (CKAN and WordPress), and it looks like the crawler does not like the wordpress pages (e.g. https://opentransportdata.swiss/de/cookbook/ or  https://opentransportdata.swiss/de/) but correctly crawls ckan pages (e.g. https://opentransportdata.swiss/de/dataset/)

**Comment by Hywan** [comment]
Hello,

The DOM is broken. However, the crawler uses regular expression, so I don't understand why it does not work yet. Searching. You might want to fix the DOM though ;-).

**Comment by Hywan** [comment]
Finally, I found what is the problem.
Sometimes, we encounter URL like `/en/log-in`, and sometimes `/en/log-in/`. When having crawling `/en/log-in`, the server responds with a 301 redirection to `/en/log-in/`, and the crawler does not like it.

I am working on a fix.

**Comment by Hywan** [comment]
Much better isn't it :-)?

![screen shot 2016-12-21 at 12 06 23-fullpage](https://cloud.githubusercontent.com/assets/946104/21386997/eca349b0-c775-11e6-83b6-61abab82101c.png)
