### ISSUE TITLE
No report created without -o option

### ISSUE THREAD

**Issue by LeBenLeBen** [liip/TheA11yMachine#87]
I’m not sure if this is a bug or intended. I’ve run `a11ym http://localhost:3000/example-pages/home.html` which succeeded (I think) but didn’t produce any report.

I’ve had to precise an output folder with `-o` to get something. I’ve seen something about `a11ym_output` being the default folder (I guess in the current directory?) but none was created by default.

**Comment by Hywan** [comment]
Indeed, we should create the default folder in the current working directory, instead of the installed directory.

**Comment by Hywan** [comment]
Thanks for the report! Will be part of the next release (coming soon), thanks for your patience!
