### ISSUE TITLE
vnu instance does not run W3C HTML ruleset

### ISSUE THREAD

**Issue by stevefaulkner** [liip/TheA11yMachine#98]
By default the vnu.jar is not built to run the W3C HTML ruleset,which i suggest it should as the W3C HTML rules include additional/different HTML conformance rules that effect accessibility of content. 
Suggest that the vnu.jar shipped with a11ymachine be built with these rules enabled - there is a python script to do this: https://github.com/validator/validator/issues/444#issuecomment-274799727

**Comment by Hywan** [comment]
Hello 🙂,

Excellent suggestion indeed. Will try to do that soon. Thanks!

**Comment by stevefaulkner** [comment]
@Hywan 
Testing this locally it doesn't run the w3c version, also when running web UI it displays the whatwg links
also this line needs updating
 `--html5link=http://www.w3.org/html/wg/drafts/html/master/single-page.html \`
to
`--html5link=http://w3c.github.io/html/single-page.html \`
\cc @sideshowbarker

**Comment by Hywan** [comment]
@stevefaulkner [`Makefile` is here](https://github.com/liip/TheA11yMachine/blob/master/resource/vnu/Makefile). Is it incorrect (except the `--html5link` option).

**Comment by sideshowbarker** [comment]
The invocation in that makefile looks to me like it should produce a W3C-enabled vnu.jar as expected

**Comment by sideshowbarker** [comment]
OK sorry for not catching this before but I remember now that to get the W3C stuff, vnu.jar must also be run with some Java system properties specified.

To run the jar for command-line checking:

```
java -Dnu.validator.servlet.follow-w3c-spec=1 \
  -Dnu.validator.spec.html5-link=http://www.w3.org/html/wg/drafts/html/master/single-page.html \
  -jar ./build/dist/vnu.jar FILES…
```

…and to run it for Web-based checking:

```
java -Dnu.validator.servlet.follow-w3c-spec=1 \
  -Dnu.validator.spec.html5-link=http://www.w3.org/html/wg/drafts/html/master/single-page.html \
  -cp ./build/dist/vnu.jar nu.validator.servlet.Main 8888
```
